# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: de77ca1eaefbec5f9e32d0e4c19a416c952921ab2f718107ee20e4853d5637e0b0cc333e882af1b23f0cc6a37940585f868036d2b807392b1c49766a29746590

test:
  secret_key_base: f438357d50d287a78b2df84748341b9c5ab3f61fce4b9c830f562ebdd0931c5a87a4bf5b07e831b84bdade1a20918d5de2c8dd534a6c3a005efd2368ae18a3e9

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
